Fix warnings on 32bit arches
Got this on i386:
```
src/libostree/ostree-repo-commit.c: In function ‘write_content_object’:
src/libostree/ostree-repo-commit.c:906:39: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘guint64 {aka long long unsigned int}’ [-Werror=format=]
             return glnx_throw (error, "min-free-space-size %luMB would be exceeded, %s more required",
                                       ^
src/libostree/ostree-repo-commit.c: In function ‘ostree_repo_prepare_transaction’:
src/libostree/ostree-repo-commit.c:1620:39: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘guint64 {aka long long unsigned int}’ [-Werror=format=]
             return glnx_throw (error, "min-free-space-size %luMB would be exceeded, %s available",
                                       ^ commit message for your changes. Lines starting
```